{% set version = "0.36.1" %}
{% set name = "S4Vectors" %}
{% set bioc = "3.16" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: db4c251e674bd7cc66f4ed9d301294b3478686436204aec9c5740e0fabd59a9a
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: IRanges, GenomicRanges, SummarizedExperiment, Matrix, DelayedArray, ShortRead, graph, data.table, RUnit, BiocStyle
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.44.0,<0.45.0'
    - r-base
    - libblas
    - liblapack
  run:
    - 'bioconductor-biocgenerics >=0.44.0,<0.45.0'
    - r-base
  build:
    - {{ compiler('c') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'Foundation of vector-like and list-like containers in Bioconductor'
  description: 'The S4Vectors package defines the Vector and List virtual classes and a set of generic functions that extend the semantic of ordinary vectors and lists in R. Package developers can easily implement vector-like or list-like objects as concrete subclasses of Vector or List. In addition, a few low-level concrete subclasses of general interest (e.g. DataFrame, Rle, Factor, and Hits) are implemented in the S4Vectors package itself (many more are implemented in the IRanges package and in other Bioconductor infrastructure packages).'
extra:
  identifiers:
    - biotools:s4vectors
    - doi:10.1038/nmeth.3252
  parent_recipe:
    name: bioconductor-s4vectors
    path: recipes/bioconductor-s4vectors
    version: 0.18.3

