{% set version = "5.9.0" %}

package:
  name: varlociraptor
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/varlociraptor/varlociraptor/archive/v{{ version }}.tar.gz
  sha256: 9768e6dd5b1b7139bdd8f4c5cf06ef9b121c7db9669b371c3d46f08be0d465f1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('rust') }}
    - rust >=1.54
    - pkg-config
    - make
    - cmake
  host:
    - gsl
    - libcblas
    - openssl
    - zlib
    - bzip2
    - xz
    - clangdev
    - blis
  run:
    - blis

test:
  commands:
    - varlociraptor -h

about:
  home: https://varlociraptor.github.io
  license: GPLv3
  license_family: GPL
  summary: Flexible, uncertainty-aware variant calling with parameter free filtration via FDR control.
