{% set version = "0.5.0" %}
{% set sha256 = "05ee547a4485017680af3819ccb2db9045a533504c4d4a0a890385c45b2cebad" %}

package:
  name: varfish-cli
  version: '{{version}}'

source:
  url: https://pypi.io/packages/source/v/varfish_cli/varfish_cli-{{version}}.tar.gz
  sha256: '{{sha256}}'

build:
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python 
  number: 0

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - attrs
    - cattrs
    - jsonschema
    - logzero
    - toml
    - requests
    - tqdm
    - tabulate
    - polyleven
    - python-dateutil
    - simplejson
    - typeguard

test:
  imports:
    - varfish_cli
  commands:
    - varfish-cli --help

about:
  home: https://github.com/bihealth/varfish-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Command line interface to VarFish via REST API
