{% set version = "3.5.2" %}

package:
  name: tiddit
  version: '{{ version }}'

source:
  url: https://github.com/SciLifeLab/TIDDIT/archive/TIDDIT-{{ version }}.tar.gz
  sha256: 4d95f5d52a1082e5ca093d3498638cdd46d66da8b523953c3f18930f7c382f2a

build:
  number: 0
  entry_points:
    - tiddit = tiddit.__main__:main
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python >=3.1
    - cython
    - numpy
    - pip
    - joblib

  run:
    - python >=3.1
    - numpy
    - joblib
    - pysam
    - fermi2
    - bwa
    - ropebwt2

test:
  commands:
    - tiddit --help
    - fermi2 2>&1 | grep "^Usage:"
    - ropebwt2 /dev/null 2>&1 | grep ropebwt2
    - bwa 2>&1 | grep "index sequences in the"
about:
  home: https://github.com/SciLifeLab/TIDDIT
  license: GPL-3.0-only
  license_file: LICENSE
  summary: "TIDDIT - structural variant calling"
